package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/base/stylebase.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"initial-scale=1.0, user-scalable=no\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <link href=\"js/jquery-easyui-1.5.1/themes/default/easyui.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <link href=\"js/jquery-easyui-1.5.1/themes/icon.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <script src=\"js/jquery-easyui-1.5.1/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/jquery-easyui-1.5.1/jquery.easyui.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("    <script src=\"js/jquery-easyui-1.5.1/locale/easyui-lang-zh_CN.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("    <link href=\"js/jquery-easyui-1.5.1/themes/color.css\" rel=\"stylesheet\"/>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        /**\r\n");
      out.write("         如果这个标题的标签存在，则选择该标签\r\n");
      out.write("         否则添加一个标签到标签组\r\n");
      out.write("         */\r\n");
      out.write("        function openTab(title, url, icon) {\r\n");
      out.write("            if ($(\"#tabs\").tabs('exists', title)) {\r\n");
      out.write("                var currTab =  self.parent.$('#tabs').tabs('getSelected'); //获得当前tab\r\n");
      out.write("                self.parent.$('#tabs').tabs('update', {\r\n");
      out.write("                    tab : currTab,\r\n");
      out.write("                    options : {\r\n");
      out.write("                        content : createTabContent(url)\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            } else {\r\n");
      out.write("                $(\"#tabs\").tabs('add', {\r\n");
      out.write("                    title: title,\r\n");
      out.write("                    content: createTabContent(url),\r\n");
      out.write("                    closable: true,\r\n");
      out.write("                    iconCls: icon\r\n");
      out.write("                });\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /* 生成标签内容 */\r\n");
      out.write("        function createTabContent(url) {\r\n");
      out.write("            return '<iframe style=\"width:100%;height:100%;overflow:hidden;\" frameborder=\"0\" src=\"' + url + '\"></iframe>';\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        /**ajax 全局配置**/\r\n");
      out.write("        $.ajaxSetup({\r\n");
      out.write("            error: function (XMLHttpRequest, textStatus, errorThrown) {\r\n");
      out.write("                if (XMLHttpRequest.status == 403) {\r\n");
      out.write("                    $.messager.alert('提示','您没有权限访问此资源或进行此操作','warning');\r\n");
      out.write("                    return false;\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            complete: function (XMLHttpRequest, textStatus) {\r\n");
      out.write("                var sessionstatus = XMLHttpRequest.getResponseHeader(\"sessionstatus\"); //通过XMLHttpRequest取得响应头,sessionstatus，\r\n");
      out.write("                if (sessionstatus == 'timeout') {\r\n");
      out.write("                    var top = getTopWinow(); //获取当前页面的顶层窗口对象\r\n");
      out.write("                    $.messager.alert('提示','登录超时, 请重新登录','warning',function () {\r\n");
      out.write("                        //如果超时就处理 ，指定要跳转的页面\r\n");
      out.write("                        top.location.href = \"login.jsp?timeout=true\"; //跳转到登陆页面\r\n");
      out.write("                    });\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        /**\r\n");
      out.write("         * 在页面中任何嵌套层次的窗口中获取顶层窗口\r\n");
      out.write("         * @return 当前页面的顶层窗口对象\r\n");
      out.write("         */\r\n");
      out.write("        function getTopWinow() {\r\n");
      out.write("            var p = window;\r\n");
      out.write("            while (p != p.parent) {\r\n");
      out.write("                p = p.parent;\r\n");
      out.write("            }\r\n");
      out.write("            return p;\r\n");
      out.write("        }\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://api.map.baidu.com/api?v=2.0&ak=UM4jTlWq8EHvSH4oVlf4W1109qbyrWId\"></script>\r\n");
      out.write("<!--加载鼠标绘制工具-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://api.map.baidu.com/library/DrawingManager/1.4/src/DrawingManager_min.css\" />\r\n");
      out.write("<!--加载检索信息窗口-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"http://api.map.baidu.com/library/SearchInfoWindow/1.4/src/SearchInfoWindow_min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://api.map.baidu.com/library/SearchInfoWindow/1.4/src/SearchInfoWindow_min.css\" />\r\n");
      out.write("<title>河道管理系统</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body,html {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tfont-family: \"微软雅黑\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#allmap {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#result {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dl,dt,dd,ul,li {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tlist-style: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("p {\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dt {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-family: \"微软雅黑\";\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tborder-bottom: 1px dotted #000;\r\n");
      out.write("\tpadding: 5px 0 5px 5px;\r\n");
      out.write("\tmargin: 5px 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("dd {\r\n");
      out.write("\tpadding: 5px 0 0 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li {\r\n");
      out.write("\tline-height: 28px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"toolbar\">\r\n");
      out.write("\t\t<div id=\"search-form\"\r\n");
      out.write("\t\t\tstyle=\"margin: 3px auto; height: 24px; line-height: 24px\">\r\n");
      out.write("\t\t\t起始时间: <input class=\"easyui-datetimebox\" id=\"dateStart\"> 结束时间:\r\n");
      out.write("\t\t\t<input class=\"easyui-datetimebox\" id=\"dateEnd\"> <a id=\"serch\"\r\n");
      out.write("\t\t\t\tonclick=\"refreshGrid()\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\t\thref=\"javascript:void(0)\" iconCls=\"icon-search\">查询</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"allmap\" style=\"overflow:hidden;zoom:1;position:relative;\">\r\n");
      out.write("\t\t<div id=\"map\"\r\n");
      out.write("\t\t\tstyle=\"height:100%;-webkit-transition: all 0.5s ease-in-out;transition: all 0.5s ease-in-out;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"add_marker\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tstyle=\"width: 380px;height: 250px;padding: 10px;left: 30%;top: 30%;\"\r\n");
      out.write("\t\tclosed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t<table align=\"center\"\r\n");
      out.write("\t\t\t\tstyle=\"border-collapse:separate; border-spacing:0px 10px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"label\"><span>桩名称:</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Name\" name=\"zhuang.name\" class=\"easyui-textbox\"\r\n");
      out.write("\t\t\t\t\t\trequired=\"true\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"label\"><span>经度:</span></td>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Longitude\" name=\"zhuang.longitude\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"label\"><span>纬度:</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Latitude\" name=\"zhuang.latitude\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>图片:</td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"file\" type=\"file\" name=\"image\"\r\n");
      out.write("\t\t\t\t\t\tonchange=\"fileChange(this);\"\r\n");
      out.write("\t\t\t\t\t\tdata-options=\"prompt:'请选择图片', buttonText:'&nbsp;&nbsp;&nbsp;&nbsp;选&nbsp;&nbsp;择&nbsp;&nbsp;&nbsp;&nbsp;'\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"width:280px\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" id=\"btn_charge\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\ticonCls=\"icon-ok\" onclick=\"addMarkerToData()\">添加</a> <a\r\n");
      out.write("\t\t\thref=\"javascript:void(0)\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\ticonCls=\"icon-cancel\" onclick=\"cancleAddmarker()\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"add_line\" class=\"easyui-dialog\"\r\n");
      out.write("\t\tstyle=\"width: 300px;height: 220px;padding: 10px;left: 30%;top: 30%;\"\r\n");
      out.write("\t\tclosed=\"true\" buttons=\"#dlg\">\r\n");
      out.write("\t\t<form id=\"form1\" method=\"post\">\r\n");
      out.write("\t\t\t<table align=\"center\"\r\n");
      out.write("\t\t\t\tstyle=\"border-collapse:separate; border-spacing:0px 10px;\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class=\"label\"><span>坐标值:</span></td>\r\n");
      out.write("\t\t\t\t\t<td><input id=\"Coordinate\" name=\"coordinate.coordinate\"\r\n");
      out.write("\t\t\t\t\t\tclass=\"easyui-textbox\" required=\"true\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"dlg\">\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" id=\"btn_addline\"\r\n");
      out.write("\t\t\tclass=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"submitForm()\">添加</a>\r\n");
      out.write("\t\t<a href=\"javascript:void(0)\" class=\"easyui-linkbutton\"\r\n");
      out.write("\t\t\ticonCls=\"icon-cancel\" onclick=\"cancleAddmarker()\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("    //限制文件上传只能是图片\r\n");
      out.write("    function fileChange(target) {\r\n");
      out.write("        var name = target.value;\r\n");
      out.write("        var fileName = name.substring(name.lastIndexOf(\".\") + 1).toLowerCase();\r\n");
      out.write("        if (fileName != \"jpg\" && fileName != \"jpeg\" && fileName != \"pdf\" && fileName != \"png\" && fileName != \"dwg\" && fileName != \"gif\") {\r\n");
      out.write("            alert(\"请选择图片格式文件上传(jpg,png,gif,dwg,pdf,gif等)！\");\r\n");
      out.write("            target.value = \"\";\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    var SEARCH_ALL = 'searchAll';\r\n");
      out.write("    //加载数据库的坐标\r\n");
      out.write("    var points = [];\r\n");
      out.write("    var markIds = [];\r\n");
      out.write("    var imgs = [];\r\n");
      out.write("    var lables = [];\r\n");
      out.write("    var marksId;\r\n");
      out.write("    //实例化地图\r\n");
      out.write("    var map = new BMap.Map('map');\r\n");
      out.write("    var opts = {anchor: BMAP_ANCHOR_TOP_LEFT,mapTypes: [BMAP_NORMAL_MAP,BMAP_SATELLITE_MAP]};\r\n");
      out.write("    \r\n");
      out.write("    //20171013宋锋使用这段代码显示地图开始\r\n");
      out.write("    var mylog = \"118.097938\";\r\n");
      out.write("    var mylat = \"37.356396\";\r\n");
      out.write("    var poi = new BMap.Point(mylog, mylat);\r\n");
      out.write("    //20171013宋锋使用这段代码显示地图结束\r\n");
      out.write("    \r\n");
      out.write("    //添加地图类型控件\r\n");
      out.write("    map.addControl(new BMap.MapTypeControl(opts));\r\n");
      out.write("\r\n");
      out.write("    map.centerAndZoom(poi, 13);\r\n");
      out.write("    map.setCurrentCity(\"滨州\");\r\n");
      out.write("    map.enableScrollWheelZoom();\r\n");
      out.write("    if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mapType}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("'===\"地图\"){\r\n");
      out.write("        map.setMapType(BMAP_NORMAL_MAP);\r\n");
      out.write("    }else if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.mapType}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("'===\"卫星\"){\r\n");
      out.write("        map.setMapType(BMAP_SATELLITE_MAP);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //显示线和点\r\n");
      out.write("    $(function () {   //页面载入时执行\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'zhuang_listData',\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("                var jsonData = result;\r\n");
      out.write("                var a = jsonData.data;\r\n");
      out.write("                for (var i in a) {\r\n");
      out.write("                    points.push(new BMap.Point(a[i].longitude, a[i].latitude));\r\n");
      out.write("                    markIds.push(a[i].id);\r\n");
      out.write("                    imgs.push(a[i].file);\r\n");
      out.write("                    lables.push(a[i].name)\r\n");
      out.write("                }\r\n");
      out.write("                for (var j = 0; j < points.length; j++) {\r\n");
      out.write("                    var point = points[j];\r\n");
      out.write("                    addMarker(point, markIds[j], imgs[j], lables[j]);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function addMarker(point, id, imgs, lables) {\r\n");
      out.write("        var myIcon = new BMap.Icon(\"images/aa.png\", new BMap.Size(40, 30));\r\n");
      out.write("        var marker = new BMap.Marker(point, {icon: myIcon});\r\n");
      out.write("        \r\n");
      out.write("        //点击桩时触发此事件\r\n");
      out.write("        marker.addEventListener(\"click\", function (e) {\r\n");
      out.write("            marksId = id;\r\n");
      out.write("\r\n");
      out.write("            var html = [];\r\n");
      out.write("\r\n");
      out.write("            if (imgs !== null) {\r\n");
      out.write("                html.push(\"<div style='width:300px;height:300px;text-align:center;'>\");\r\n");
      out.write("                html.push(\"<h4 style='margin:0 0 5px 0;padding:0.2em 0'>提示</h4>\");\r\n");
      out.write("                html.push(\"<img style='margin:4px' id='imgDemo' src='upload/zhuang/\" + imgs + \"' width='280' height='300' title='桩'/>\");\r\n");
      out.write("            }else {\r\n");
      out.write("                html.push(\"<div style='width:300px;text-align:center;'>\");\r\n");
      out.write("                html.push(\"<h4 style='margin:0 0 5px 0;padding:0.2em 0'>提示</h4>\");\r\n");
      out.write("            }\r\n");
      out.write("            html.push(\"<input type='button' value='删除' onclick='deletePoint()'>\");\r\n");
      out.write("            html.push(\"<br/>\");\r\n");
      out.write("            html.push(\"</div>\");\r\n");
      out.write("            var inWindow = new BMap.InfoWindow(html.join(\"\"));  // 创建信息窗口对象\r\n");
      out.write("            this.openInfoWindow(inWindow);\r\n");
      out.write("            inWindow.redraw(); //防止在网速较慢，图片未加载时，生成的信息框高度比图片的总高度小，导致图片部分被隐藏\r\n");
      out.write("        });\r\n");
      out.write("        map.addOverlay(marker);\r\n");
      out.write("        var label = new BMap.Label(lables, {offset: new BMap.Size(20, -10)});\r\n");
      out.write("        marker.setLabel(label);\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //删除桩点\r\n");
      out.write("    function deletePoint() {\r\n");
      out.write("        $.messager.confirm('Confirm', '你确定要删除这个桩吗?', function (r) {\r\n");
      out.write("            if (r) {\r\n");
      out.write("                var md = marksId;\r\n");
      out.write("                $.post('zhuang_deletePost', {\"zhuang.id\": md}, function (result) {\r\n");
      out.write("                    if (result.success) {\r\n");
      out.write("                        location.href = \"add.jsp\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $.messager.alert(\"错误\", \"操作失败！\" + result.message, \"error\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, 'json');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //显示河道\r\n");
      out.write("    var linePoints = [];\r\n");
      out.write("    var coordinate = [];\r\n");
      out.write("    var strs = [];\r\n");
      out.write("    var str = [];\r\n");
      out.write("    var lineId = [];\r\n");
      out.write("    $(function () {   //页面载入时执行\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'coordinate_selectPost',\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("                var jsonData = data;\r\n");
      out.write("                var a = jsonData.data;\r\n");
      out.write("                for (var i in a) {  //将每个数据库添加到数组中去\r\n");
      out.write("                    linePoints.push(a[i].coordinate);\r\n");
      out.write("                    lineId.push(a[i].id);\r\n");
      out.write("                }\r\n");
      out.write("                for (var j = 0; j < linePoints.length; j++) {  //针对每条记录画线 \r\n");
      out.write("                    var point = linePoints[j];\r\n");
      out.write("                    addLine(point, lineId[j]);    //调用画线的方法\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    //添加线\r\n");
      out.write("    function addLine(point, id) {\r\n");
      out.write("        strs = point.split(\"|\");\r\n");
      out.write("        for (var s = 0; s < strs.length; s++) {\r\n");
      out.write("            str = strs[s].split(\",\");\r\n");
      out.write("            coordinate.push(new BMap.Point(str[0], str[1]));\r\n");
      out.write("        }\r\n");
      out.write("        var polyline = new BMap.Polyline(coordinate\r\n");
      out.write("            , {strokeColor: \"red\", strokeWeight: 5, strokeOpacity: 0.5});   //创建折线\r\n");
      out.write("        coordinate.length = 0;\r\n");
      out.write("        map.addOverlay(polyline);   //增加折线\r\n");
      out.write("        polyline.addEventListener(\"click\", function () {\r\n");
      out.write("            deleteLine(id);\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("     //删除河道\r\n");
      out.write("    function deleteLine(marksId) {                                   \r\n");
      out.write("        $.messager.confirm('删除确认', '您确定要删除这条折线吗?',\r\n");
      out.write("            function (r) {\r\n");
      out.write("                if (r) {\r\n");
      out.write("                    var md = marksId;  \r\n");
      out.write("                    $.post('coordinate_deletePost', {\"coordinate.id\": md}, function (result) {\r\n");
      out.write("                        if (result.success) {\r\n");
      out.write("                            location.href = \"add.jsp\";\r\n");
      out.write("                        } else {\r\n");
      out.write("                            $.messager.alert(\"错误\", \"操作失败！\" + result.message, \"error\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }, 'json');\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //实例化鼠标绘制工具\r\n");
      out.write("    var overlays = [];\r\n");
      out.write("    var polylinecomplete = function (e, overlay) {\r\n");
      out.write("        overlays.push(overlay);\r\n");
      out.write("        getPoint();\r\n");
      out.write("\r\n");
      out.write("        $('#add_line').dialog('open').dialog('center').dialog('setTitle', '添加坐标值');\r\n");
      out.write("\r\n");
      out.write("    };\r\n");
      out.write("    var myIcon = new BMap.Icon(\"images/aa.png\", new BMap.Size(40, 30));\r\n");
      out.write("    var styleOptions = {\r\n");
      out.write("        icon: myIcon,\r\n");
      out.write("        strokeColor: \"red\",    //边线颜色。\r\n");
      out.write("        fillColor: \"red\",      //填充颜色。当参数为空时，圆形将没有填充效果。\r\n");
      out.write("        strokeWeight: 3,       //边线的宽度，以像素为单位。\r\n");
      out.write("        strokeOpacity: 0.8,\t   //边线透明度，取值范围0 - 1。\r\n");
      out.write("        fillOpacity: 0.6,      //填充的透明度，取值范围0 - 1。\r\n");
      out.write("        strokeStyle: 'solid' //边线的样式，solid或dashed。\r\n");
      out.write("    };\r\n");
      out.write("    var drawingManager = new BMapLib.DrawingManager(map, {\r\n");
      out.write("        isOpen: false, //是否开启绘制模式\r\n");
      out.write("        enableDrawingTool: true, //是否显示工具栏\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        drawingToolOptions: {\r\n");
      out.write("            anchor: BMAP_ANCHOR_TOP_RIGHT, //位置\r\n");
      out.write("            offset: new BMap.Size(5, 5), //偏离值\r\n");
      out.write("            drawingModes: [BMAP_DRAWING_MARKER, BMAP_DRAWING_POLYLINE],\r\n");
      out.write("            drawingTypes: []\r\n");
      out.write("        },\r\n");
      out.write("\r\n");
      out.write("        polylineOptions: styleOptions,//线的样式\r\n");
      out.write("        markerOptions: styleOptions\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    drawingManager.addEventListener('polylinecomplete', polylinecomplete);\r\n");
      out.write("\r\n");
      out.write("\t //得到坐标值\r\n");
      out.write("    function getPoint() {                                         \r\n");
      out.write("        var f;\r\n");
      out.write("        f = null;\r\n");
      out.write("        for (var i = 0; i < overlays.length; i++) {\r\n");
      out.write("            var overlay = overlays[i].getPath();\r\n");
      out.write("\r\n");
      out.write("            for (var j = 0; j < overlay.length; j++) {\r\n");
      out.write("                var grid = overlay[j];\r\n");
      out.write("\r\n");
      out.write("                if (j == overlay.length - 1) {\r\n");
      out.write("\r\n");
      out.write("                    f = f + grid.lng + \",\" + grid.lat;\r\n");
      out.write("                    break;\r\n");
      out.write("                }\r\n");
      out.write("                f = f + grid.lng + \",\" + grid.lat + \"|\";\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("            $('#Coordinate').textbox('setValue', f);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //添加桩点\r\n");
      out.write("    var markercomplete = function (e, overlay) {\r\n");
      out.write("        clearOldMarker();\r\n");
      out.write("        overlays.push(overlay);\r\n");
      out.write("        showAddMarkerDialog(e);\r\n");
      out.write("    };\r\n");
      out.write("    drawingManager.addEventListener(\"markercomplete\", markercomplete);\r\n");
      out.write("\r\n");
      out.write("    var clearOldMarker = function () {\r\n");
      out.write("        for (var i = 0; i < overlays.length; i++) {\r\n");
      out.write("            map.removeOverlay(overlays[i]);\r\n");
      out.write("        }\r\n");
      out.write("        overlays.length = 0;\r\n");
      out.write("    };\r\n");
      out.write("    var showAddMarkerDialog = function (e) {\r\n");
      out.write("        $('#Longitude').textbox('setValue', e.point.lng);\r\n");
      out.write("        $('#Latitude').textbox('setValue', e.point.lat);\r\n");
      out.write("        $('#add_marker').dialog('open').dialog('center').dialog('setTitle', '添加桩点');\r\n");
      out.write("    };\r\n");
      out.write("    var cancleAddmarker = function () {\r\n");
      out.write("        clearOldMarker();\r\n");
      out.write("        $('#add_marker').dialog('close');\r\n");
      out.write("    };\r\n");
      out.write("    \r\n");
      out.write("     //添加桩点\r\n");
      out.write("    var addMarkerToData = function () {                         \r\n");
      out.write("        var Longitude = $(\"#Longitude\").val();\r\n");
      out.write("        var Latitude = $(\"#Latitude\").val();\r\n");
      out.write("        var name = $(\"#Name\").val();\r\n");
      out.write("        if (Longitude === null || Longitude === \"\") {\r\n");
      out.write("            $.messager.alert(\"提示\", \"请选择经度\", \"error\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (Latitude === null || Latitude === \"\") {\r\n");
      out.write("            $.messager.alert(\"提示\", \"请选择纬度\", \"error\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("        if (name === null || name === \"\") {\r\n");
      out.write("            $.messager.alert(\"提示\", \"请输入桩名称\", \"error\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('#fm').form('submit', {\r\n");
      out.write("            url: \"zhuang_addPost\",\r\n");
      out.write("            success: function (r) {    \r\n");
      out.write("                $.messager.progress('close');\r\n");
      out.write("                if (r === null) return;\r\n");
      out.write("                r = $.parseJSON(r);\r\n");
      out.write("                if (r.success) {\r\n");
      out.write("                    $('#add_marker').dialog('close');\r\n");
      out.write("                    $.messager.alert(\"提示\", r.message, \"info\", function () {\r\n");
      out.write("                        location.href = \"zhuang_add?mapType=\"+map.getMapType().cf;\r\n");
      out.write("                    });\r\n");
      out.write("                } else {\r\n");
      out.write("                    $.messager.alert(\"提示\", r.message, \"error\");\r\n");
      out.write("                    $('#fm').dialog('close');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("\t//添加河道\r\n");
      out.write("    function submitForm() {                                         //画线\r\n");
      out.write("        var Coordinate = $(\"#Coordinate\").val();\r\n");
      out.write("\r\n");
      out.write("        if (Coordinate === null || Coordinate === \"\") {\r\n");
      out.write("            $.messager.alert(\"提示\", \"请选择经度\", \"error\");\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $('#form1').form('submit', {\r\n");
      out.write("            url: \"coordinate_createPost\",\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            success: function (r) {\r\n");
      out.write("                $.messager.progress('close');\r\n");
      out.write("                if (r === null) return;\r\n");
      out.write("                r = $.parseJSON(r);\r\n");
      out.write("                if (r.success) {\r\n");
      out.write("                    $('#add_line').dialog('close');\r\n");
      out.write("                    $.messager.alert(\"提示\", r.message, \"info\", function () {\r\n");
      out.write("                        location.href = \"zhuang_add?mapType=\"+map.getMapType().cf;\r\n");
      out.write("                    });\r\n");
      out.write("                } else {\r\n");
      out.write("                    $.messager.alert(\"提示\", r.message, \"error\", window.location.reload());\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //显示标记为1的警报点\r\n");
      out.write("    var markIdj = [];\r\n");
      out.write("    var pointj = [];\r\n");
      out.write("    var imagej = [];\r\n");
      out.write("    var contentj = [];\r\n");
      out.write("    var videoj = [];\r\n");
      out.write("    var audioj = [];\r\n");
      out.write("    var creatTimeArr = [];\r\n");
      out.write("    var uploaderArr = [];\r\n");
      out.write("    var markjId;\r\n");
      out.write("    //从后台获取巡视过程中发现的问题\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'warn_showData',\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("                var a = result.data;\r\n");
      out.write("                for (var item in a) {\r\n");
      out.write("                    pointj.push(new BMap.Point(a[item].longitude, a[item].latitude));\r\n");
      out.write("                    imagej.push(a[item].file);\r\n");
      out.write("                    contentj.push(a[item].description);\r\n");
      out.write("                    videoj.push(a[item].video);\r\n");
      out.write("                    markIdj.push(a[item].id);\r\n");
      out.write("                    audioj.push(a[item].audio);\r\n");
      out.write("                    creatTimeArr.push(a[item].createtime);\r\n");
      out.write("                    uploaderArr.push(a[item].uploaderName);\r\n");
      out.write("                }\r\n");
      out.write("                for (var j = 0; j < pointj.length; j++) {\r\n");
      out.write("                    var pt = pointj[j];\r\n");
      out.write("                    addMarker(pt, markIdj[j], contentj[j], imagej[j], videoj[j], audioj[j], creatTimeArr[j], uploaderArr[j]);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                function addMarker(pt, id, description, image, video, audio, createtime, uploader) {\r\n");
      out.write("                    var marker = new BMap.Marker(pt, 15);//创建标注\r\n");
      out.write("                    marker.addEventListener(\"click\", function () {\r\n");
      out.write("                            markjId = id;\r\n");
      out.write("                            var html = [];\r\n");
      out.write("                            html.push(\"<div style='width:300px;height:300px;text-align:center;'>\");\r\n");
      out.write("                            html.push(\"<h4 style='margin:0 0 5px 0;padding:0.2em 0'>提示</h4>\");\r\n");
      out.write("                            if (image !== null) {\r\n");
      out.write("                                html.push(\"<img style='margin:4px' id='imgDemo' src='/upload/warn/\" + image + \"' width='280' height='300'; title='警告'/><br/>\");\r\n");
      out.write("                            }else {\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            html.push(\"<span>\" + description + \"</span><br/>\");\r\n");
      out.write("                            if (audio !== null) {\r\n");
      out.write("                                html.push(\"<span>此信息附有音频<a href='/jsp/zhuang/audioPlay.jsp?audioAdress=/upload/warn/\" + audio + \"' target='_blank'>单击查看</a></span><br/>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if (video !== null) {\r\n");
      out.write("                                html.push(\"<span>此信息附有视频<a href='/jsp/zhuang/videoPlay.jsp?videoAdress=/upload/warn/\" + video + \"' target='_blank'>单击查看</a></span>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            html.push(\"<input type='button' value='关闭报警' onclick='closePoint()'>\");\r\n");
      out.write("                            html.push(\"<br/>\");\r\n");
      out.write("                            html.push(\"<span>上传人：\" + uploader + \"</span>\");\r\n");
      out.write("                            html.push(\"<br/>\");\r\n");
      out.write("                            html.push(\"<span>上传时间：\" + createtime + \"</span>\");\r\n");
      out.write("                            html.push(\"</div>\");\r\n");
      out.write("                            var inWindow = new BMap.InfoWindow(html.join(\"\"));  // 创建信息窗口对象\r\n");
      out.write("                            this.openInfoWindow(inWindow);\r\n");
      out.write("                            document.getElementById('imgDemo').onload = function () {\r\n");
      out.write("                                infoWindow.redraw();   //防止在网速较慢，图片未加载时，生成的信息框高度比图片的总高度小，导致图片部分被隐藏\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    );\r\n");
      out.write("                    map.addOverlay(marker);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        })\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    //关闭警告点\r\n");
      out.write("    function closePoint() {\r\n");
      out.write("        $.messager.confirm('Confirm', '你确定关闭报警点吗?', function (r) {\r\n");
      out.write("            if (r) {\r\n");
      out.write("                var mk = markjId;\r\n");
      out.write("                $.post('warn_updatePost', {\"warn.id\": mk}, function (result) {\r\n");
      out.write("                    if (result.success) {\r\n");
      out.write("                        location.href = \"add.jsp\";\r\n");
      out.write("                    } else {\r\n");
      out.write("                        $.messager.alert(\"错误\", \"操作失败！\" + result.message, \"error\");\r\n");
      out.write("                    }\r\n");
      out.write("                }, 'json');\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //显示全部的警报点\r\n");
      out.write("    $(function () {\r\n");
      out.write("        if ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.router}", java.lang.String.class, (PageContext)_jspx_page_context, null, false));
      out.write("' === SEARCH_ALL) {\r\n");
      out.write("            $.ajax({\r\n");
      out.write("                url: 'warn_showAllData',\r\n");
      out.write("                success: function (result) {\r\n");
      out.write("                    var a = result.data;\r\n");
      out.write("                    for (var i in a) {\r\n");
      out.write("                        pointj.push(new BMap.Point(a[i].longitude, a[i].latitude));\r\n");
      out.write("                        imagej.push(a[i].file)\r\n");
      out.write("                        contentj.push(a[i].description);\r\n");
      out.write("                        videoj.push(a[i].video);\r\n");
      out.write("                        markIdj.push(a[i].id);\r\n");
      out.write("                        audioj.push(a[i].audio);\r\n");
      out.write("                        creatTimeArr.push(a[i].createtime);\r\n");
      out.write("                        uploaderArr.push(a[i].uploaderName);\r\n");
      out.write("                    }\r\n");
      out.write("                    for (var j = 0; j < pointj.length; j++) {\r\n");
      out.write("                        var pt = pointj[j];\r\n");
      out.write("                        addMarker(pt, markIdj[j], contentj[j], imagej[j], videoj[j], audioj[j], creatTimeArr[j], uploaderArr[j]);\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    function addMarker(pt, id, description, image, video, audio, createtime, uploader) {\r\n");
      out.write("                        var marker = new BMap.Marker(pt, 15);//创建标注\r\n");
      out.write("                        marker.addEventListener(\"click\", function () {\r\n");
      out.write("                            markjId = id;\r\n");
      out.write("                            var html = [];\r\n");
      out.write("                            html.push(\"<div style='width:300px;height:300px;text-align:center;'>\");\r\n");
      out.write("                            html.push(\"<h4 style='margin:0 0 5px 0;padding:0.2em 0'>提示</h4>\");\r\n");
      out.write("                            if (image !== null) {\r\n");
      out.write("                                html.push(\"<img style='margin:4px' id='imgDemo' src='/upload/warn/\" + image + \"' width='280' height='300'; title='警告'/><br/>\");\r\n");
      out.write("                            }else {\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                                html.push(\"<span></span><br/>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            html.push(\"<span>\" + description + \"</span><br/>\");\r\n");
      out.write("                            if (audio !== null) {\r\n");
      out.write("                                html.push(\"<span>此信息附有音频<a href='/jsp/zhuang/audioPlay.jsp?audioAdress=/upload/warn/\" + audio + \"' target='_blank'>单击查看</a></span><br/>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            if (video !== null) {\r\n");
      out.write("                                html.push(\"<span>此信息附有视频<a href='/jsp/zhuang/videoPlay.jsp?videoAdress=/upload/warn/\" + video + \"' target='_blank'>单击查看</a></span>\");\r\n");
      out.write("                            }\r\n");
      out.write("                            html.push(\"<input type='button' value='关闭报警' onclick='closePoint()'>\");\r\n");
      out.write("                            html.push(\"<br/>\");\r\n");
      out.write("                            html.push(\"<span>上传人：\" + uploader + \"</span>\");\r\n");
      out.write("                            html.push(\"<br/>\");\r\n");
      out.write("                            html.push(\"<span>上传时间：\" + createtime + \"</span>\");\r\n");
      out.write("                            html.push(\"</div>\");\r\n");
      out.write("                            var inWindow = new BMap.InfoWindow(html.join(\"\"));  // 创建信息窗口对象\r\n");
      out.write("                            this.openInfoWindow(inWindow);\r\n");
      out.write("                            document.getElementById('imgDemo').onload = function () {\r\n");
      out.write("                                infoWindow.redraw();\r\n");
      out.write("                            }\r\n");
      out.write("                        });\r\n");
      out.write("                        map.addOverlay(marker);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    //查询使用\r\n");
      out.write("    function refreshGrid() {\r\n");
      out.write("        var dateStart = $(\"#dateStart\").datebox('getValue');\r\n");
      out.write("        var dateEnd = $(\"#dateEnd\").datebox('getValue');\r\n");
      out.write("        map.clearOverlays();\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url: 'warn_refresh',\r\n");
      out.write("            data: {\"dateStartId\": dateStart, \"dateEndId\": dateEnd},\r\n");
      out.write("            dataType: \"json\",\r\n");
      out.write("            type: 'post',\r\n");
      out.write("            success: function (result) {\r\n");
      out.write("                var a = result.data;\r\n");
      out.write("                for (var i in a) {\r\n");
      out.write("                    pointj.push(new BMap.Point(a[i].longitude, a[i].latitude));\r\n");
      out.write("                    imagej.push(a[i].file)\r\n");
      out.write("                    contentj.push(a[i].description);\r\n");
      out.write("                    videoj.push(a[i].video);\r\n");
      out.write("                    markIdj.push(a[i].id);\r\n");
      out.write("                    audioj.push(a[i].audio);\r\n");
      out.write("                    creatTimeArr.push(a[i].createtime);\r\n");
      out.write("                    uploaderArr.push(a[i].uploaderName);\r\n");
      out.write("                }\r\n");
      out.write("                for (var j = 0; j < pointj.length; j++) {\r\n");
      out.write("                    var pt = pointj[j];\r\n");
      out.write("                    addMarker2(pt, markIdj[j], contentj[j], imagej[j], videoj[j], audioj[j], creatTimeArr[j], uploaderArr[j]);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function addMarker2(pt, id, description, image, video, audio, createtime, uploader) {\r\n");
      out.write("        var marker = new BMap.Marker(pt, 15);//创建标注\r\n");
      out.write("        marker.addEventListener(\"click\", function () {\r\n");
      out.write("            var html = [];\r\n");
      out.write("            html.push(\"<div style='width:300px;height:300px;text-align:center;'>\");\r\n");
      out.write("            html.push(\"<h4 style='margin:0 0 5px 0;padding:0.2em 0'>提示</h4>\");\r\n");
      out.write("            if (image !== null) {\r\n");
      out.write("                html.push(\"<img style='margin:4px' id='imgDemo' src='/upload/warn/\" + image + \"' width='280' height='300'; title='警告'/><br/>\");\r\n");
      out.write("            }else {\r\n");
      out.write("                html.push(\"<span></span><br/>\");\r\n");
      out.write("                html.push(\"<span></span><br/>\");\r\n");
      out.write("                html.push(\"<span></span><br/>\");\r\n");
      out.write("            }\r\n");
      out.write("            html.push(\"<span>\" + description + \"</span><br/>\");\r\n");
      out.write("            if (audio !== null) {\r\n");
      out.write("                html.push(\"<span>此信息附有音频<a href='/jsp/zhuang/audioPlay.jsp?audioAdress=/upload/warn/\" + audio + \"' target='_blank'>单击查看</a></span><br/>\");\r\n");
      out.write("            }\r\n");
      out.write("            if (video !== null) {\r\n");
      out.write("                html.push(\"<span>此信息附有视频<a href='/jsp/zhuang/videoPlay.jsp?videoAdress=/upload/warn/\" + video + \"' target='_blank'>单击查看</a></span>\");\r\n");
      out.write("            }\r\n");
      out.write("            html.push(\"<input type='button' value='关闭报警' onclick='closePoint()'>\");\r\n");
      out.write("            html.push(\"<br/>\");\r\n");
      out.write("            html.push(\"<span>上传人：\" + uploader + \"</span>\");\r\n");
      out.write("            html.push(\"<br/>\");\r\n");
      out.write("            html.push(\"<span>上传时间：\" + createtime + \"</span>\");\r\n");
      out.write("            html.push(\"</div>\");\r\n");
      out.write("            var inWindow = new BMap.InfoWindow(html.join(\"\"));  // 创建信息窗口对象\r\n");
      out.write("            this.openInfoWindow(inWindow);\r\n");
      out.write("            document.getElementById('imgDemo').onload = function () {\r\n");
      out.write("                infoWindow.redraw();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        map.addOverlay(marker);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
